### ISSUE TITLE
Shenanigans

### ISSUE THREAD

**Issue by VarshithRV** [abishekdevendran/talk-do#6]
Bro on the grind
![fXryqX_6_400x400](https://github.com/abishekdevendran/talk-do/assets/97271639/1e0add04-b9a5-4cf9-bced-7ed0596696f5)

**Comment by abishekdevendran** [comment]
@VarshithRV naw bro contributed to the repo before my hackathon teammates 😂

**Comment by VarshithRV** [comment]
Imma go ahead an close it lol
